### ISSUE TITLE
update factory

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1168]
... to 4.1.3 by 1.16

**Comment by mahrud** [comment]
I updated the CMake build to use factory 4.1.3 from Singular, which I added to that branch as a submodule. The old patch is no longer necessary, but I submitted this PR to fix an issue on their end: https://github.com/Singular/Sources/pull/996

The only problem is that the Singular repository is about 120MB whereas the subdirectory containing factory is only about 7MB. Flint is similar; the repository is 40MB but a tarfile is only 4MB. If you make a tarfile again, could you keep the name of the directory "factory" instead of "factory-4.1.3"? That would make it easier to switch between using a tarfile and using a submodule.

PS: @mikestillman do we use the template types in ftmpl_inst.cc anywhere? `libraries/factory/Makefile.in` seems to imply we need it.

**Comment by mahrud** [comment]
The Singular PR is merged. We should be able to just use upstream in autotools as well.

**Comment by DanGrayson** [comment]
> I updated the CMake build to use factory 4.1.3 from Singular, which I added to that branch as a submodule. The old patch is no longer necessary, but I submitted this PR to fix an issue on their end: [Singular/Sources#996](https://github.com/Singular/Sources/pull/996)
> 

4.1.3 breaks one of our tests, so the two builds cannot use different versions. 

> The only problem is that the Singular repository is about 120MB whereas the subdirectory containing factory is only about 7MB. Flint is similar; the repository is 40MB but a tarfile is only 4MB. If you make a tarfile again, could you keep the name of the directory "factory" instead of "factory-4.1.3"? That would make it easier to switch between using a tarfile and using a submodule.

That's the name in their tarfile, but I could investigate renaming it.

**Comment by mahrud** [comment]
> 4.1.3 breaks one of our tests, so the two builds cannot use different versions.

Which tests? Actually, the two builds use different sources and versions for a number of libraries, so I don't think this would be a problem.

> That's the name in their tarfile, but I could investigate renaming it.

I guess I assumed you make the tarfile from the repository, and in the repository the directory is factory (perhaps they changed this recently?)

**Comment by DanGrayson** [comment]
> > 4.1.3 breaks one of our tests, so the two builds cannot use different versions.
> 
> Which tests? Actually, the two builds use different sources and versions for a number of libraries, so I don't think this would be a problem.
> 

I think it's one of the chapters in the book that fails.  Anyway, if you're content for one of the cmake tests to fail until I upgrade the factory library to 4.1.3 and fix that test, then we're good.

I don't know what you mean by not being a problem.  It's a problem if a test fails.

> > That's the name in their tarfile, but I could investigate renaming it.
> 
> I guess I assumed you make the tarfile from the repository, and in the repository the directory is factory (perhaps they changed this recently?)

No, Hannes makes the tar file and posts it on their website.  It's there now.

**Comment by mahrud** [comment]
Is this (and hence #1320) getting postponed to v1.18?

**Comment by mahrud** [comment]
The CMake build has been using 4.1.3 without any issues. The ComputationsBook test is resolved now.
