### ISSUE TITLE
Definition of some unicode symbols

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1186]
I'm about to do a PR and found this in my code:
```
export { "ℚ","ℝ","ℤ","ℂ","∞" }
ℚ=QQ
ℝ=RR
ℤ=ZZ
ℂ=CC
∞=infinity
```
This wasn't meant to be shipped, so a priori, I'll remove it.
But I was wondering, do people think it's a good idea?

**Comment by DanGrayson** [comment]
That would be fine, but let's make them synonyms, rather than separate symbols, as here:
```
export {
	-- synonyms:
        "ann" => "annihilator",
        "ass" => "associatedPrimes",
        "coker" => "cokernel",
        "det" => "determinant",
        "gens" => "generators",
        "ker" => "kernel",
        "minPres" => "minimalPresentation",
        "numcols" => "numColumns",
        "numrows" => "numRows",
        "res" => "resolution",
        "sub" => "substitute",
        "top" => "topComponents"
}
```

Hmm, how can the user control which one is displayed on the screen when printing?  We probably don't want the unicode to be displayed by default, but it would be great to have the option available.

There are also various unicode operators we could consider introducing as synonyms for existing ones, such as `⊗` for `**`.

**Comment by pzinn** [comment]
Ah yes, synonyms of course.
Because of #1069 it is indeed not a good idea to use the unicode by default.
Leaving this aside for now, will get back to it when I look into #1069.

**Comment by pzinn** [comment]
Aha! as to ⊗ for **, I tried but failed.
I had indeed added as well
```
	"⊗" => "**"
```
but then `x ⊗ x` will work but not `x⊗x` ...

**Comment by DanGrayson** [comment]
In d/lex.d the function gettoken1 gets the next token, and it uses isalnum and isalpha to recognize identifiers, which are supposed start with an alphabetic character and have some alphnumeric characters after that.  The problem is it doesn't distinguish unicode characters at all, treating all bytes bigger than 127 as alphabetic (a unicode character is a sequence of up to 4 bytes, each bigger than 127 -- see the function utf8 in parser.d for the conversion scheme).  What needs to be done is to figure out which part of the unicode characters ought to be considered as alphabetic, and which ought to be considered as symbols.  Well, Chinese characters are not alphabetic, but they can be parts of words.  The job of "recognize" is to use a finite state machine to recognize the operators, so you have to add the new operators to the file binding.d, with the right parsing precedence.  Forget about making them synonyms with older, non-unicode operators.  Alternatively, we could install the same symbol in the finite state machine under multiple character sequences, to get the same effect as synonyms.  But, synonyms are perhaps not such good idea: what we think of as synonyms might not be regarded as synonyms by others.
