### ISSUE TITLE
confusing branch

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1188]
@mikestillman - I bet you didn't intend to create a branch named "PD" on this repository.  Can you keep it on your fork instead?

**Comment by mahrud** [comment]
Speaking of branches, I think we can use tags instead of branches for new releases, so the branch list doesn't get longer and longer. In particular, no commits are made to each release branch after the release, so they don't need to be branches. We also track releases [here](https://github.com/Macaulay2/M2/releases), so perhaps older release branches could be removed (I didn't check that every release branch has an equivalent release on the releases page.)

Also, it would be great to sift through the stale branches, keep what is still relevant as a PR and remove those that aren't. Here are the stale ones:

- `furnish-parallel3` is also tracked [here](https://github.com/garyfurnish/M2/tree/furnish-parallel3) and is 4 commits, which might be comparable, but some of the changes seem to be already in master.
- `furnish-Parallel2` is also tracked [here](https://github.com/garyfurnish/M2/tree/furnish-Parallel2) and is 9839 commits ahead and commits behind master, so I don't know how to compare the changes.
- `furnish-parallel` is also tracked [here](https://github.com/garyfurnish/M2/tree/furnish-parallel) and has 83 new commits, mostly in the M2-tex directory. If that is still relevant, we could put that in a separate repository or in a directory named `contrib` for related, but unsupported, tools.
- `scons` is also tracked [here](https://github.com/garyfurnish/M2/tree/scons) and seems to implement a SCons build system.
- `scons-cpp` is also tracked [here](https://github.com/garyfurnish/M2/tree/scons-cpp) and is a about 30 commits behind the one above.
- `givaro-ffpack` has 2 commits that update givaro and ffpack versions, but we've already done that in the eigen branch. 
- `gmp-default-alloc` has 2 new commits, https://github.com/Macaulay2/M2/commit/31770e4a703c24ce906b7d9547f6bfef05727137 and https://github.com/Macaulay2/M2/commit/6d25955e4451a09397721e90d6d9b8f181af6f3d, related to refactoring the engine and some TODO notes which would be good to keep track of as issues.
- `reducedgb-dec2017` has this new commit: https://github.com/Macaulay2/M2/commit/0360a70de1375ff09570981e1afed2bab0f1e666 and it could be rebased and made into a PR.
- `res2017` this one doesn't seem to have any new commits, only many commits behind.
- `try-not-patching-mpir` is 11 commits ahead and many behind. Not sure which commits are still relevant.

**Comment by DanGrayson** [comment]
Thanks!  Gary Furnish's github account could disappear at any time, so it might be worth keeping his stuff for evaluation by anyone.

I don't know how github's releases page  works -- it seems just to be a list of tags.  In any case, if we want to keep track of something, it should be in the repository itself -- we might not always be using github.

The problem with trying to make something like "release-1.15" a tag instead of a branch is that there can be changes to OS's that need to be counteracted so we can prepare distributions.  It is true, though, that more of the work I do to get a release ready could be done on the development/master branches, such as adding the changes documentation node for that release and adding the stars to the packages that have been published.

I've deleted try-not-patching-mpir -- we've done that already.

Mike can look at the other ones and save them on his repository if needed.

**Comment by mahrud** [comment]
> I don't know how github's releases page works -- it seems just to be a list of tags. In any case, if we want to keep track of something, it should be in the repository itself -- we might not always be using github.

Each release is just a tag, which is intrinsic to the git repository. You can optionally add other stuff on github, but you don't need to.

> The problem with trying to make something like "release-1.15" a tag instead of a branch is that there can be changes to OS's that need to be counteracted so we can prepare distributions. It is true, though, that more of the work I do to get a release ready could be done on the development/master branches, such as adding the changes documentation node for that release and adding the stars to the packages that have been published.

I didn't understand this. We already have plenty of releases as tags listed here: https://github.com/Macaulay2/M2/releases. If you're suggesting that new commits can be added to a branch after the release has been made, I think that's a bad idea, because then there would be a mismatch between the tag and branch for that version. If there are changes that need to be made after a release tag is made, we would just bump the patch version and make a new tag.

Regardless, I don't imagine there would be any more changes to branches `release-1.0` through `release-1.14`, which already gave release tags, so they are unnecessary.

> Thanks! Gary Furnish's github account could disappear at any time, so it might be worth keeping his stuff for evaluation by anyone.

I looked through again, and I think the `parallel` branches were accidentally pushed to this repository, since the changes seem to have been already merged in 4d58e76cf88591cd340d9c95d5b18863adc21f0d and 5b471b4d1721ba6ed1d0b5dddedc4b148294d305 (see the dates on these commits vs. the last commit on those branches).

The `scons-cpp` branch is definitely unnecessary since it's just a few commits behind `scons`, and `scons` itself is too far behind to be usable, especially given that cmake is about to be merged. You could track `scons` on your fork, perhaps?

**Comment by DanGrayson** [comment]
> > I don't know how github's releases page works -- it seems just to be a list of tags. In any case, if we want to keep track of something, it should be in the repository itself -- we might not always be using github.
> 
> Each release is just a tag, which is intrinsic to the git repository. You can optionally add other stuff on github, but you don't need to.
> 
> > The problem with trying to make something like "release-1.15" a tag instead of a branch is that there can be changes to OS's that need to be counteracted so we can prepare distributions. It is true, though, that more of the work I do to get a release ready could be done on the development/master branches, such as adding the changes documentation node for that release and adding the stars to the packages that have been published.
> 
> I didn't understand this. We already have plenty of releases as tags listed here: https://github.com/Macaulay2/M2/releases. If you're suggesting that new commits can be added to a branch after the release has been made, I think that's a bad idea, because then there would be a mismatch between the tag and branch for that version. If there are changes that need to be made after a release tag is made, we would just bump the patch version and make a new tag.
> 

I don't regard those as releases.  Those are tags whose names start with "version-", as far as I can tell.  The releases are branch whose names start with "release-".

> Regardless, I don't imagine there would be any more changes to branches `release-1.0` through `release-1.14`, which already gave release tags, so they are unnecessary.

Well, we still have to be able to find them, so we can't just delete them.  Perhaps you imagine that `release-1.14` is a synonym of `version-1.14`.


> 
> > Thanks! Gary Furnish's github account could disappear at any time, so it might be worth keeping his stuff for evaluation by anyone.
> 
> I looked through again, and I think the `parallel` branches were accidentally pushed to this repository, since the changes seem to have been already merged in [4d58e76](https://github.com/Macaulay2/M2/commit/4d58e76cf88591cd340d9c95d5b18863adc21f0d) and [5b471b4](https://github.com/Macaulay2/M2/commit/5b471b4d1721ba6ed1d0b5dddedc4b148294d305) (see the dates on these commits vs. the last commit on those branches).
> 

If one of those branches is included in "master", then we don't need it, of course.  But I'm not sure that's what you're saying.

> The `scons-cpp` branch is definitely unnecessary since it's just a few commits behind `scons`, and `scons` itself is too far behind to be usable, especially given that cmake is about to be merged. You could track `scons` on your fork, perhaps?

Not on my fork: I'm not the only one in the world who might consider making a build system based on scons (which is pretty cool).

**Comment by DanGrayson** [comment]
PS: If we could figure out how to stop github's Releases page from showing all the tags that start with "version-", that would be helpful.

**Comment by mikestillman** [comment]
> @mikestillman - I bet you didn't intend to create a branch named "PD" on this repository. Can you keep it on your fork instead?

That is correct.  @DanGrayson Can you remove it from Macaulay2/M2.git ?

**Comment by DanGrayson** [comment]
Done.
