### ISSUE TITLE
Build changes CacheExampleOutput files in repository

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1216]
After every build, every .out file in CoincidentRootLoci changes. See the diff here:
https://gist.github.com/mahrud/e0b1a39621e278ea3e160b70d83ed933

Almost all are trivial differences:
```
diff --git a/M2/Macaulay2/packages/CoincidentRootLoci/examples/_complexrank.out b/M2/Macaulay2/packages/CoincidentRootLoci/examples/_complexrank.out
index 115c761a2..1f43703ea 100644
--- a/M2/Macaulay2/packages/CoincidentRootLoci/examples/_complexrank.out
+++ b/M2/Macaulay2/packages/CoincidentRootLoci/examples/_complexrank.out
@@ -1,7 +1,4 @@
 -- -*- M2-comint -*- hash: -1413194878
-***************************************************************************
-CoincidentRootLoci v.0.1.1 loaded successfully (last updated: June 1, 2018)
-***************************************************************************
 
 i1 : R := QQ[x,y];
 
@@ -46,7 +43,7 @@ o2 = 325699392019820093805938500473136959995883x   -
 o2 : QQ[x, y]
 
 i3 : time complexrank F
-     -- used 0.129225 seconds
+     -- used 0.246214 seconds
 
 o3 = 8
```

There is only one nontrivial change:
```
diff --git a/M2/Macaulay2/packages/CoincidentRootLoci/examples/_realroots.out b/M2/Macaulay2/packages/CoincidentRootLoci/examples/_realroots.out
index f34c497aa..eb144454d 100644
--- a/M2/Macaulay2/packages/CoincidentRootLoci/examples/_realroots.out
+++ b/M2/Macaulay2/packages/CoincidentRootLoci/examples/_realroots.out
@@ -1,7 +1,4 @@
 -- -*- M2-comint -*- hash: -2142234149
-***************************************************************************
-CoincidentRootLoci v.0.1.1 loaded successfully (last updated: June 1, 2018)
-***************************************************************************
 
 i1 : F = randomBinaryForm 5
 
@@ -14,7 +11,7 @@ o1 : QQ[t , t ]
 
 i2 : realroots F
 
-o2 = {[-.495276, 1]}
+o2 = {}
 
 o2 : List
 ```
But even this is generating a random degree 5 polynomial in two variables and finding real roots, so why would it ever be the same?

**Comment by DanGrayson** [comment]
It would be good to remove those "time" commands.  For any package caching example output, it is essential.

The random polynomial should be (and appears to be) the same, since we always run examples with the `--no-randomize` option.  (Otherwise we set a random number seed at the start based on the date and time or something like that.)

If the polynomial is the same and the roots are not, there must be a bug now.

**Comment by mahrud** [comment]
`--no-randomize` only affects M2, but not the libraries and programs we use. This package, in particular, uses the `qepcad` program.

**Comment by DanGrayson** [comment]
There doesn't seem to be a way to tell qepcad not to randomize, and the source code for qepcad seems to be unchanged since 2012, so we probably can't convince anyone to add that feature.  (I can't even figure out how it does randomize.  Does it really?)  Anyway, at least we can remove those "time" commands.

**Comment by mahrud** [comment]
There's more now, a bunch in Bertini and one in NumericalSchubertCalculus:

[CachedExampleOutput.diff.txt](https://github.com/Macaulay2/M2/files/5139487/CachedExampleOutput.diff.txt)

**Comment by DanGrayson** [comment]
Looking at that, it seems that the printWidth has changed, too, which is mysterious.
