### ISSUE TITLE
upgrade normaliz

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1239]
... to version 3.8.5

**Comment by DanGrayson** [comment]
@mahrud -- how are we going to keep the two build systems in sync on package versions?

**Comment by mahrud** [comment]
I presume you mean libraries and programs? Should that be a requirement?
e.g. currently the CMake build builds normaliz 3.8.4 (vs. autotools build
at 3.7.2). I'll push a commit to bump it to 3.8.5 on that end.

My suggestion is that the autotools build could take advantage of the CMake
build's `make build-libraries` target, since CMake makes looking for
required libraries, building them, and imposing dependencies much easier.
Other targets like `make build-normaliz-test` can also be used for `make
check`

**Comment by DanGrayson** [comment]
It would be a good idea to keep the versions in sync, for then examples and tests that work under one build system will be more likely to work under the other.

**Comment by mahrud** [comment]
Closing in favor of #1517.
