### ISSUE TITLE
the two build systems should build the same versions of programs and libraries

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1243]
It would be a good idea to keep the versions in sync, for then examples and tests that work under one build system will be more likely to work under the other.

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/issues/1239#issuecomment-639517382_

**Comment by mikestillman** [comment]
In particular, the basic defaults should be the same: either both should use mpir, or both use gmp.

**Comment by mahrud** [comment]
Are there recent benchmarks of which is faster? I know Sage uses mpir by default and I believe @dimpase had thoughts on this.

**Comment by dimpase** [comment]
Sage's current default is to use a system-wide GMP installation (it can actually be MPIR in GMP-compatible mode), and nudge the user to install GMP if it's not installed (by printing a message to this effect at the end of `./configure`'s run).

My understanding is that MPIR's development is mostly on hold, since appearance of Meltdown and Spectre attack on Intel CPUs, rendering efforts to optimise MPIR's assembly routines (something that made them faster than GMP) problematic, as it was assumed that extensive CPU's patching needed to mitigate against these attacks would break them. 

I don't know whether this prediction came to be true, perhaps @wbhart can comment.

**Comment by mahrud** [comment]
Referencing  #475, which is about using OpenBLAS. The CMake build uses OpenBLAS if it is present.

**Comment by mahrud** [comment]
@DanGrayson #475 is still remaining.
