### ISSUE TITLE
fflas-ffpack givaro mismatch

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1261]
@mahrud- could you take a look at the failure in https://github.com/Macaulay2/M2/runs/763702275 ?  I believe the problem is that the givaro library we have is too old to contain the function `sumofsquaresmodprime` that fflas-ffpack is not asking for, most likely since one of the several updates to fflas-ffpack that you have made in the last month.

**Comment by mahrud** [comment]
The reason I updated fflas-ffpack is that it wasn't working with gcc 10.
Easiest fix here would be to also build givaro from a submodule, but I don't know how to do that in the autotools build.

**Comment by mahrud** [comment]
One more thing: we actually can't use packaged versions of fflas-ffpack and givaro at the moment, because they have a bug that makes them unusable with gcc10, despite the fact that they have been distributed on systems with gcc10. The only solutions are:
1. use the upstream version via submodule (what CMake does)
2. use the latest release tag but add a patch commit (or use a tarfile and distribute a patch)

I prefer first option, since the patch is already in it, but if you prefer to use a official but patched release, you also have the second option.

When they distribute a new release, we can go back to using their tarfiles or distributed packages.

**Comment by DanGrayson** [comment]
Submodules are good, let's stick with them.

**Comment by mahrud** [comment]
Should this be closed?

**Comment by DanGrayson** [comment]
Yes, closing.
