### ISSUE TITLE
MethodFunctionWithOptions that takes OptionTable as input

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1441]
Is the title possible? I suspect not, but I'm wondering if there's a hidden trick involving calling `installMethod` directly.
```m2
fun = method(Options => {X => 1})

fun ZZ := ZZ => opts -> n -> n * opts.X
2 == fun 2
4 == fun(2, X=>2)

fun HashTable := ZZ => opts -> h -> h.Y * opts.X
2 == fun new HashTable from {Y => 2}
4 == fun(new HashTable from {Y => 2}, X => 2)

-- declaration works fine:
fun OptionTable := ZZ => opts -> h -> h.Y * opts.X
-- calls result in error: encountered an unknown key or option: Y
fun new OptionTable from {Y => 2}
fun(new OptionTable from {Y => 2}, X => 2)
fun(X => 2, new OptionTable from {Y => 2})
```

**Comment by mahrud** [comment]
This came up because I changed `select` to have options, but at least in one place `select(HashTable, Function)` was used to filter through an `OptionTable`, which resulted in an error. The fix was easy, just `select(new HashTable from opts, opt -> ...)`, but I'm wondering if there's a way around it that doesn't potentially break any code.

**Comment by DanGrayson** [comment]
I think there's no way around it, because the handling of options has to be done at a low level, in order to determine the method function to call.  Similarly, there would be no way to apply "select" to a list of type Option.

How about adding a line to the documentation of (select, BasicList, Function) and (select, HashTable, Function) mentioning this new wrinkle?
