### ISSUE TITLE
replace now a MethodFunctionWithOptions

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1492]
apparently `replace` is now a `MethodFunctionWithOptions`. unfortunately this breaks existing code, e.g.,
```
i1: replace(0, a=>1, {b=>2,c=>3}) -- should (and used to) output {a=>1,c=>3}

stdio:34:1:(3): error: no method found for applying replace to:
     argument 1 :  0 (of class ZZ)
     argument 2 :  {b => 2, c => 3} (of class List)
```
any reason this change has been made?
because if so, a lot of code needs checking...

**Comment by mahrud** [comment]
The reason was to take options for regex:
```m2
i2 : options (replace, String, String, String)

o2 = OptionTable{POSIX => false}
```
Also for `(select, String, String)` and `(select, , String, String, String)`.

It's annoying that parsing options is not done at the top level, but the interpreter, since the interpreter doesn't know what are the options for the method, otherwise `a=>1` would not be consumed as an option for a method that doesn't take any options.

**Comment by pzinn** [comment]
sure, it's easy to fix, but there may be many such issues in the existing code.
an example:
```
i54 : style( SPAN { "hello", "style"=>"background:yellow" }, "font-weight" => "bold" )

stdio:57:1:(3): error: no method found for applying replace to:
     argument 1 :  1 (of class ZZ)
     argument 2 :  {hello, style => background:yellow} (of class List)
```

**Comment by mahrud** [comment]
Yes, that's always the case with any change, which is why there should be tests written for all exported functions.

In any case, I don't think use of class `Option` in a list as opposed to an OptionTable or HashTable is correct, and probably all Hypertext objects should use option tables rather than a list of options. Then you can use `override` for changing an option rather searching in a list.

**Comment by pzinn** [comment]
I don't disagree, the current internal structure of Hypertext objects is not great. But barring (another!) complete rewrite...
I will fix that particular instance of the issue (style) when I have time, and add a test as suggested.

**Comment by DanGrayson** [comment]
To get this to work:
```m2
i2 : replace(0, a=>1, {b=>2,c=>3})

o2 = {a => 1, c => 3}
```
the way it used to, it would be sufficient to fix the way method functions with optional named arguments work, so that the named arguments have to come at the end.  Then here, where the object of type Option is in the middle, it would be dispatched as before.

This wouldn't be a great loss -- I think in the vast majority of the code written, the options go at the end of the list
of arguments, anyway.

**Comment by pzinn** [comment]
yes, sounds good.

**Comment by DanGrayson** [comment]
The main question would be whether the change would slow things down a lot.

**Comment by pzinn** [comment]
maybe we should just leave things the way they are. closing.
