### ISSUE TITLE
global variable lastMatch

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1504]
`lastMatch` is a global variable. this, we can all agree on, is bad.
One particular problem is that if output routines use `regex`, then the content of `lastMatch` will not be preserved (unless we do some ugly backup process which doesn't resolve the underyling thread-safety issue).
This is unfortunately the case in WebApp mode:
```
i9 : topLevelMode=WebApp

o9 =  WebApp 

o9 :   Symbol  

i10 : match ("asd", "--asd--")


o10 =   true  

i11 : lastMatch
```
(i.e., `lastMatch` is null instead of the expected answer).

I would urge to deprecate `lastMatch` and find some cleaner alternative.

**Comment by pzinn** [comment]
incidentally the latest version of the `match` help example won't run at all in web app mode because it asks for `substring(first lastMatch, s)` (and `lastMatch` is always `null`).

**Comment by mahrud** [comment]
It would be good to make this a caveat of `lastMatch`, but perhaps not deprecate it. Does webapp work if you don't use `match` and instead just use `regex`?

**Comment by DanGrayson** [comment]
Yes, it's bad -- in particular, it's not thread safe.  It should go.

**Comment by mahrud** [comment]
perhaps there should be a way to make top level variables thread local without going into `d`.

**Comment by pzinn** [comment]
> It would be good to make this a caveat of `lastMatch`, but perhaps not deprecate it. Does webapp work if you don't use `match` and instead just use `regex`?

I'll look into it.

**Comment by pzinn** [comment]
> > It would be good to make this a caveat of `lastMatch`, but perhaps not deprecate it. Does webapp work if you don't use `match` and instead just use `regex`?
> 
> I'll look into it.

As a workaround, replacing
```
htmlLiteral = s -> if s === null or not match("<|&|]]>|\42", s)l then s else (
```
with
```
htmlLiteral = s -> if s === null or regex("<|&|]]>|\42", s) === null then s else (
```
solves the webapp issue, yes. but not the underlying issue.

**Comment by pzinn** [comment]
I think we all agree on the underlying issue, but it is unlikely to get fixed any time soon, since there are plenty of other thread-unsafe code in M2. closing.

**Comment by DaveBarton** [comment]
I think we should declare global variables like `lastMatch` to be a `threadVariable` (which makes it thread-local, initialized to `null` in each thread). Then routines like your output routine could save/restore `lastMatch` and it'd work fine (ignoring interrupts/exceptions), without disturbing other threads. Routines that wanted to communicate `lastMatch` between threads would have to do so explicitly.

Or we could just get rid of global variables like `lastMatch`, especially since it's easy to return multiple values from a function in M2, instead of setting a separate global variable.

In general, we'd like to get rid of the thread-unsafe code in M2, at least for generally useful (library-type) functions.

**Comment by DaveBarton** [comment]
@d-torrance See my last comment.

**Comment by d-torrance** [comment]
Makes sense to me!

Outside of documentation and tests, I think `lastMatch` is used exactly once (in the `RandomObjects` package), so it's probably safe to remove.
