### ISSUE TITLE
Examples being run with --no-preload

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1543]
Maybe there's already an issue out there mentioning these problems, but since I haven't found any, here it is.
Some examples seem to rely on certain packages. Here's one: `resolution-doc.m2` tries
`ideal"a3-ab-c2,abc-d2-1, b3-b2-b"` which fails with
```
currentString:10:5:(3):[25]: error: no method found for applying ideal to:
     argument   :  "a3-ab-c2,abc-d2-1, b3-b2-b" (of class String)
```
because the package `Classic` has not been loaded.

**Comment by DanGrayson** [comment]
Yes, I think there's not much point in trying to run package installation without preloading the usually-preloaded packages.  So we don't.

This doesn't happen to you unless you try something like that, by editing the source code, does it?

**Comment by mahrud** [comment]
I recently added --no-preload for all packages except Macaulay2Doc. It would be good if Macaulay2Doc also didn't need it though, since it has the most number of documentation nodes and preloading time adds up. We decided it's best to instead fix the capture command so we can run examples in the same process rather than starting a new Macaulay2. The problem with that currently is that cleaning dictionaries is confusing.

**Comment by pzinn** [comment]
oh OK. never mind then. it does run fine now, I must've done something weird. closing.

**Comment by mahrud** [comment]
Wait, actually, now I can't find in which PR I made that change. I distinctly remember making the change, but I don't see it in the code! I'll reopen so this can be fixed.

**Comment by mahrud** [comment]
Ah, I think I stashed that change because some packages had missing dependencies and it was taking too much work to fix them all. I just made a new PR to fix it, though it'll need more work to get all packages and tests to run.

**Comment by mahrud** [comment]
Thanks for bringing this up again! By the way, the previous issue that discussed this was #1181.
