### ISSUE TITLE
some error messages are ignored by emacs

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1719]
... because they are printed after a line without a terminating newline character, as here:

<img width="1317" alt="Screen Shot 2020-12-19 at 7 12 32 AM" src="https://user-images.githubusercontent.com/700228/102690278-de600a00-41c9-11eb-8de7-12979cf205e5.png">

**Comment by DanGrayson** [comment]
And lots of lines are flagged by emacs as errors, even though they aren't.

**Comment by DanGrayson** [comment]
Also, this is too noisy, by a factor of 2:

<img width="870" alt="Screen Shot 2020-12-19 at 7 16 27 AM" src="https://user-images.githubusercontent.com/700228/102690316-267f2c80-41ca-11eb-8920-deb1d7885335.png">

**Comment by mahrud** [comment]
> ... because they are printed after a line without a terminating newline character, as here:

The "ignored error" that you mention shouldn't be printed at all! They are printed because `capture` isn't handling standard error output correctly. Once that is fixed, you wouldn't see those errors until all tests are run, then you see a summary of errors.

> And lots of lines are flagged by emacs as errors, even though they aren't.

I don't think we can do anything about this, unless you'd like to:
- not print the path at all, or
- change the way clickable paths are detected in M2-mode, so paths after `--` are also clickable.

> Also, this is too noisy, by a factor of 2:

Well, it used to be too noisy by a factor of 3, so that's an improvement!

I would be okay with not printing the paths, since the location of failing tests is printed in the end anyway, but I'll defer to @d-torrance to decide that.

For package documentation, I extended `locate` to show me the location of the documentation:
```m2
i1 : locate makeDocumentTag benchmark

o1 = (../../../../Macaulay2/packages/./Macaulay2Doc/./debugging.m2, 386, , , , , )
```
Eventually I wanted to set up a system so tests of a given function can also be located similarly, but that hasn't happened yet.

**Comment by d-torrance** [comment]
> I would be okay with not printing the paths, since the location of failing tests is printed in the end anyway, but I'll defer to @d-torrance to decide that.

That sounds good to me.  As long as we get lots of info for failing tests, I'm happy.  :)
