### ISSUE TITLE
checking a package changes the namespace

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1787]
The following code appears to assign a value to `f`.

```
needsPackage "Complexes"
check Complexes
f
```

**Comment by mahrud** [comment]
Ah, it's because I'm passing the `UserMode` option of `check` to `capture`:
https://github.com/Macaulay2/M2/blob/9a7832bc6d77020eb146e93899afc8617644dee7/M2/Macaulay2/m2/testing.m2#L43

If you do `check(Complexes, UserMode => false)` it should go away.

But perhaps we should change this. Either default value of `[check, UserMode]` should be false, or `check` should always pass `UserMode => false` to capture. Which would you prefer?
