### ISSUE TITLE
MinimalPrimes crash

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#190]
This test can crash:

```
  needsPackage "MinimalPrimes"
  R = QQ[x,r,v,u,b, MonomialOrder=>{Lex=>5}]
  I = ideal(b^3-7*b^2+14*b-7,r^2-u*r+(-2*b^2+9*b-5)*u^2+b^2-4*b,x^2+(b-2)*x*r+r^2+b^2-4*b)
  time minprimes(I, Verbosity=>2)

  R = QQ[b][u][x,r,v, MonomialOrder=>{Lex=>3}]
  I = ideal(b^3-7*b^2+14*b-7,r^2-u*r+(-2*b^2+9*b-5)*u^2+b^2-4*b,x^2+(b-2)*x*r+r^2+b^2-4*b)
  time minprimes(I, Verbosity=>2)
```

**Comment by mikestillman** [comment]
This works for me, under macosx.  It is likely working now because of the recent changes to factory.  I'll close this issue, but will reopen it, if it still crashes on other machines.  I have added it to the tests for the MinimalPrimes package.  However, it takes about 15 seconds to run, so maybe it should be placed in the "slow" directory.

**Comment by DanGrayson** [comment]
Fails under gcc 5.3.1 in fedora 23, as reported by @dimpase, so reopening --
see https://github.com/Macaulay2/M2/issues/334#issuecomment-241397806

**Comment by d-torrance** [comment]
It might be worth re-opening this issue to track any proress on `MinimalPrimes` tests 14 and 74:

https://github.com/Macaulay2/M2/issues/1742#issuecomment-753691617

**Comment by d-torrance** [comment]
> It might be worth re-opening this issue to track any progress on `MinimalPrimes` tests 14 and 74:
> 
> [#1742 (comment)](https://github.com/Macaulay2/M2/issues/1742#issuecomment-753691617)

Actually, never mind -- there's already an open issue for this (#1064).
