### ISSUE TITLE
M2 in papers: beautification of `M2-merge`

### ISSUE THREAD

**Issue by antonleykin** [Macaulay2/M2#1972]
@DanGrayson wrote https://github.com/Macaulay2/M2-merge to automate insertion of M2 input/output in LaTeX articles.
It would be nice to have the output produced by `texMath` and automatically processed. 

@pzinn, that would be similar to what https://github.com/pzinn/Macaulay2Web does.

**Comment by pzinn** [comment]
proof of concept: given this (where code is in verbatim)

[notes.pdf](https://github.com/Macaulay2/M2/files/7634927/notes.pdf)

the script (written in m2) outputs this:

[notes-parsed.pdf](https://github.com/Macaulay2/M2/files/7634932/notes-parsed.pdf)

is this what you had in mind?

**Comment by antonleykin** [comment]
Yep, this looks nice!

**Comment by pzinn** [comment]
working on it:
https://github.com/pzinn/M2inTeX

**Comment by pzinn** [comment]
oh, I just realize in the title it referred to M2-merge. I just wrote this from scratch, no relation to M2-merge.

**Comment by mahrud** [comment]
Would be nice if this worked nicely with the output of `installPDF` (see [book.m2](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/m2/book.m2)).

**Comment by pzinn** [comment]
@mahrud I've just realized something: there's no reliable way to match the input and the output of `capture`. for example, I can easily fool it by creating a multi-line input
```
f=i->(
i+1)
```
and then all examples will be shifted... I've tried it as part of a package documentation and sure enough it breaks the documentation. I'm having the same issue with my texparser since it's also based on `capture`.

**Comment by mahrud** [comment]
Why not?
```m2
i5 : s = "f=i->(\ni+1)\nf(2)"

o5 = f=i->(
     i+1)
     f(2)

i6 : separateM2output last capture s

o6 = {i1 : f=i->(         , i2 : f(2), i3 : }
           i+1)
                            o2 = 3
      o1 = f

      o1 : FunctionClosure

o6 : List
```

**Comment by pzinn** [comment]
the problem is not at the level of `separateM2output`. it's later when one tries to identify the input and the output.
try to insert in documentation something like
```
Text
 test1
Example
 f=i->(
 i+1
 )
Text
 test2
Example
 xxxxxxxxxx
```
and `installPackage`, you should have the same problem I had I think?

**Comment by mahrud** [comment]
Oh I see what you mean. No, that's just a caveat of SimpleDoc, I believe. Try this:
```m2
document {Key => "hello", "test1", EXAMPLE "f=i->(\ni+1\n)\n", "test2", EXAMPLE "f(2)"}
help "hello"
```
The problem is that SimpleDoc doesn't know how to parse that example into multiple individual commands, so it defaults to splitting the lines by indentation groups, which isn't always correct. Try this, as the dual to the example you had:
```m2
doc ///
Key
  "bye"
Description
  Text
    "test1"
  Example
    1
      2
     3
    4
  Text
    "test2"
  Example
     5
///
help "bye"
```
It could probably have a couple more heuristics, like matching parenthesis and brackets, but I think my plan was to eventually skip the separation of the example inputs altogether and just throw it all into capture and separate the output from there. This should always work, I believe, but it'll take some work.

**Comment by mahrud** [comment]
Ah, I remembered the problem with implementing this: in my last example above, you can capture example blocks 1..4 and 5 easily and separate the outputs into a list with 5 elements, but the problem is how to tell how many of the output lines need to go in the first example block in the documentation and how many in the second.

The main solution I can think of is to capture in two chunks: capture 1..4, save the state (dictionary, etc), make an example block, then recover the state and capture 5 and make the second example block.

Does that make sense? I don't have a clean solution to this, so for now kindly asking that people correctly indent their examples in SimpleDoc input seems vastly easier :stuck_out_tongue:

**Comment by pzinn** [comment]
I agree that I intentionally messed up the indentation.
It does seem that the clean solution would be to capture successive chunks, but maybe that's too complicated to implement, you would know better than I.
I'll think of a workaround for my tex parsing code.

**Comment by pzinn** [comment]
After multiple rewrites, I think I found a pretty good way to deal with the issues above in
https://github.com/pzinn/M2inTeX
working pretty well, I'm using it for a course I'm giving now on computerized mathematical exploration...

**Comment by DanGrayson** [comment]
Looks pretty good, but I'm not sure I like all those blue rectangles.

**Comment by pzinn** [comment]
The nice thing about using the package `listings` is, you can format the output any way you like. e.g. if you don't like the blue rectangles in the example file, you can remove them by commenting out `frame=leftline` in the `\lstset` list of options.

**Comment by DanGrayson** [comment]
Can this be a Macaulay2 package?

**Comment by pzinn** [comment]
sure can. what would be a good name for it?

**Comment by DanGrayson** [comment]
Well, if it's a Macaulay2 package, it doesn't have to have Macaulay2 in its name -- maybe TeXmerge or MergeTeX.

**Comment by pzinn** [comment]
I think this can be closed now -- MergeTeX works decently.
