### ISSUE TITLE
Ext(Module,Module) can give error if c = 0

### ISSUE THREAD

**Issue by xlni** [Macaulay2/M2#2003]
For example:
```
S = QQ[x,y,z]
M = S^1/ideal(x,y,z)
Ext(M,M)
```
returns "error: expected degrees of length 0."

Culprit in the code for ```Ext(Module,Module)``` seems to be ```basis(d,R)``` not liking it when R is a polynomial ring on zero variables (c=0).

**Comment by mahrud** [comment]
I think this is vaguely related to #1312. Note that `basis(0, QQ[])` gives an error but the following works:
```m2
i2 : basis({}, QQ[])

o2 = | 1 |

                  1            1
o2 : Matrix (QQ[])  <--- (QQ[])
```
I can add a change in #1929 so `basis(0, M)` always converts 0 to the appropriate zero list for the given module.

The alternative would be to change `Ext` so it calls `basis({}, QQ[])` when `d=0`, but using zero as a replacement for the zero vector sounds easier to me.

**Comment by mahrud** [comment]
Actually, after trying to implement this, I think it's more complicated. For instance, over `S = QQ[]`, I would expect `basis({0}, S^1)` to be `{1}` and `basis({4}, S^1)` to be zero, but what about `basis({4}, S^{-4})`? Since it is generated in degree 4, the basis should be `{1}` again. I can think of a cursory way to fix this in top level, but it really needs a fix in the engine so it accepts degrees other than `{}`. @jkyang92 what do you think?

**Comment by jkyang92** [comment]
While the error is coming from the engine, it's because it infers the degree length from the heft vector it's given. And for some reason, on line 700 in modules2.m2 inside the `findHeftandVars`, there's a special case to return {} as the heft vector if there are no variables.

This might be because the basis code in the engine doesn't really like zero heft vectors, and if you run the remainder of the code in `findHeftandVars` you get a heft vector with all zeros of length `ndegs`.

It seems the easiest fix is to have findHeftandVars return a heft vector with all ones of length `ndeg` in that special case.

**Comment by mahrud** [comment]
Ah, good catch! I fixed that same issue in `findHeft`, but missed this one. My top level basis PR is rewriting this section, so I'll include it in there.
