### ISSUE TITLE
Problem with substitutions in fraction fields

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2245]
(though there is a vague ressemblance with my #2208 and #2215 I think it's mostly unrelated -- well, except for the fact that trying to invert an integer should produce an error message and not some weird answer)
this fails:
```
i1 : R=frac(ZZ[u]);

i2 : sub(u^-1,u=>-12)

o2 = -1

i3 : sub(u^-1,u=>31)

o3 = 0
```
`sub` tries to build a map from ZZ to ZZ and fails miserably. for the record, this will work fine:
```
i4 : R=frac(ZZ[u,v])

o4 = R

o4 : FractionField

i5 : sub(u^-1,u=>-12)

     -1
o5 = --
     12

o5 : R

i6 : sub(u^-1,u=>31)

      1
o6 = --
     31

o6 : R
```
since it creates a map from R to R.

my point with this issue is, the code for "guessing" the right ring in sub2 (ringmap.m2) might need to be improved.

**Comment by DanGrayson** [comment]
It was intentional from an early stage that ring "homomorphisms" need not be well defined and would just do something when applied to a ring element.  I think that's a remnant of an earlier day when lifting elements from the target to the source was done by making a wrong-way "homomorphism".  I'd like to change that eventually.  @mikestillman may have the opposite opinion.

**Comment by pzinn** [comment]
The fact remains, Macaulay2 currently produces a mathematically wrong result.
