### ISSUE TITLE
real functions applied to constants

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2404]
this should work, but doesn't:
```
i1 : sqrt pi
stdio:1:1:(3): error: expected a real number

i2 : sin pi
stdio:2:1:(3): error: expected a number
```

**Comment by DanGrayson** [comment]
Yes, and by default, it should convert pi to the precision given by the variable `defaultPrecision`.

The code for sin and sqrt, etc., is in not top-level, but when getting something of an unexpected top-level type, it could look up a method for handling it, so that code installed by statement like `sin Constant := x -> sin numeric(defaultPrecision, x)` would come into play.

**Comment by DanGrayson** [comment]
Alternatively, the internal function `sin` could be renamed to `sin'`, and a new top-level method function `sin` could be created, with methods for Number and Constant.

**Comment by pzinn** [comment]
I can try to take care of that.

**Comment by mahrud** [comment]
My two cents:
- why can't `Constant` inherit from `Number` instead? It seems counter-intuitive because `pi` and `ii` are a `Constant` but `-pi` and `-ii` are `RR` and `CC`. Is this the best way to deal with constants?
- organizationally, I would rather move all compiled real and complex valued functions moved out of "actors3.d" into something like "reals.d" instead, and maybe even do away with the typical values kludge altogether.

**Comment by pzinn** [comment]
For the first point, AFAICT it's not possible to have new types descending from `Number`... but I'm sure you know that already.
I agree with the second point, some reorganization will be needed once this matter is settled.
