### ISSUE TITLE
MultiplierIdeals package doesn't work

### ISSUE THREAD

**Issue by AviSteiner** [Macaulay2/M2#2454]
I am using Macaulay2 version 1.19.1. I get the following error:

```
i1 : needsPackage "MultiplierIdeals"
MultiplierIdeals.m2:143:17:(2):[11]: error: assignment to protected built-in global variable 'multiplierIdeal'
```

**Comment by DanGrayson** [comment]
I can't reproduce that here.  Perhaps you have a corrupted version of the file "MultiplierIdeals.m2" in your current directory.

**Comment by denham0** [comment]
@DanGrayson I've got Macaulay2 version 1.19.1 running on OS X as well as Ubuntu 16.04.  The error @AviSteiner notes happens for me only on my Ubuntu 16.04 system (perhaps the same distribution he's using.)  Not on my Mac.

**Comment by AviSteiner** [comment]
> @DanGrayson I've got Macaulay2 version 1.19.1 running on OS X as well as Ubuntu 16.04. The error @AviSteiner notes happens for me only on my Ubuntu 16.04 system (perhaps the same distribution he's using.) Not on my Mac.

I'm using Ubuntu 20.04.3 LTS (GNU/Linux 5.8.0-63-generic x86_64)

**Comment by DanGrayson** [comment]
Could you try adding "-q" to the M2 command line and try again?

We haven't released a version of M2 for Ubuntu 16.04 since 2019.  How did you get M2 1.19.1 installed there?

**Comment by denham0** [comment]
Sorry, it’s actually 18.04.  Maybe my brain missed an update.

This is what I get:

***@***.***:~$ M2 -q
Macaulay2, version 1.19.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra,
               Saturation, TangentCone

i1 : needsPackage "MultiplierIdeals"
--warning: symbol "Classic" in PackageDictionary is shadowed by a symbol in HyperplaneArrangements.Dictionary
--  use the synonym Package$Classic

o1 = MultiplierIdeals

o1 : Package

i2 :

**Comment by DanGrayson** [comment]
The effect of "-q" on the command line is to omit the user "application directory" from the path.  That's where packages get installed when you run "installPackage" on them.  So maybe you have an old version of MultiplierIdeals there, since with "-q" the package loads correctly.  You could try

`uninstallPackage "MultiplierIdeals"`

to get rid of it, or 

`uninstallAllPackages()`

to get rid of all previously installed packages.

**Comment by denham0** [comment]
Thanks, it turns out it was a conflict coming from the development version of HyperplaneArrangements.

**Comment by DanGrayson** [comment]
I'm glad it worked out.

**Comment by AviSteiner** [comment]
> I'm glad it worked out.

Well, it hasn't quite worked out yet. Graham, Greg, and I still need to figure out what we did that's making this happen. The only thing I can think of is that we have some exports with the same name as exports from MultiplierIdeals, but that shouldn't make a difference.

**Comment by DanGrayson** [comment]
Try setting `notify = true` before loading it, so you can see which file is actually being loaded.  Better yet, add `--notify` to the M2 command line to see which version of everything else is being loaded.

**Comment by DanGrayson** [comment]
Okay, here's what's happening.

You have installed a modern version of the package HyperplaneArrangements, which now exports `multiplierIdeal`.  (It also exports `multIdeal`, which seems to be a bad idea, since the names are so similar.)

The package MultiplierIdeals depends on the package HyperplaneArrangements, so when MultiplierIdeals is being loaded, it first loads HyperplaneArrangements.  The dictionary path while MultiplierIdeals is being loaded is this:

```m2
        {HyperplaneArrangements.Dictionary    }
        {Matroids.Dictionary                  }
        {Posets.Dictionary                    }
        {FourTiTwo.Dictionary                 }
        {Graphs.Dictionary                    }
        {SimplicialComplexes.Dictionary       }
        {GenericInitialIdeal.Dictionary       }
        {Normaliz.Dictionary                  }
        {ReesAlgebra.Dictionary               }
        {MultiplierIdeals#"private dictionary"}
        {MultiplierIdeals.Dictionary          }
        {Core.Dictionary                      }
        {OutputDictionary                     }
        {PackageDictionary                    }
```

Notice that the dictionary for HyperplaneArrangements occurs before the dictionary for MultiplierIdeals in the path.  That means, that when the statement
```m2
multiplierIdeal = method();
```
is encountered, it looks up the symbol multiplierIdeal in the dictionaries on the path, and finds the one in HyperplaneArrangements, which has already been exported and marked immutable.  Thus the assignment leads to an error.

One way to go is to just remove the line `multiplierIdeal = method();` from the package MultiplierIdeals.  Then you could just add more methods to the method function of that name provided by HyperplaneArrangements.  (Don't override any methods, though -- we're going to disallow that.)

(If you are actively developing the package HyperplaneArrangements, then it's logical that you might have to modify other packages that depend on it.)

(I was wrong before, when I assumed that exporting the symbol before using it would make it work.)

**Comment by AviSteiner** [comment]
@DanGrayson  `multIdeal` is a synonym for `multiplierIdeal`. It's only there for backwards compatibility. 

I did what you suggested, and now everything works. **However**: `logCanonicalThreshold` as defined in MultiplierIdeals _does_ override the definition from `HyperplaneArrangements'. How do I deal with this so that things don't go wrong later?

**Comment by AviSteiner** [comment]
@ggsmith (Just to loop you in)

**Comment by ggsmith** [comment]
I'm in the process of fixing this issue as I prepare a pull request for our new version of HyperplaneArrangements.

**Comment by AviSteiner** [comment]
> I'm in the process of fixing this issue as I prepare a pull request for our new version of HyperplaneArrangements.

I've already "fixed" it, modulo the problem with overriding `logCanonicalThreshold`. I also found a bug in `trim`, which I fixed. I'll push everything now.

**Comment by DanGrayson** [comment]
> @DanGrayson `multIdeal` is a synonym for `multiplierIdeal`. It's only there for backwards compatibility.
> 
> I did what you suggested, and now everything works. **However**: `logCanonicalThreshold` as defined in MultiplierIdeals _does_ override the definition from HyperplaneArrangements. How do I deal with this so that things don't go wrong later?

Get together with the authors of the other package and decide whose code is better, then eliminate one in favor of the other.

**Comment by DanGrayson** [comment]
> > @DanGrayson `multIdeal` is a synonym for `multiplierIdeal`. It's only there for backwards compatibility.

There is a way to create a true synonym in the list of exports:

```m2
    "isDecomposable", 
    "isCentral", 
    "multiplierIdeal",
    "multIdeal" => "multiplierIdeal",
    "lct",
    "logCanonicalThreshold",
    "randomArrangement",
```

See https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.19.1/share/doc/Macaulay2/Macaulay2Doc/html/_export.html
