### ISSUE TITLE
cddplus

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#2506]
I wonder whether we still need to build and include cddplus.  Is it being used anywhere by anybody for anything?

@ggsmith -- you wanted this eventually -- do you still?

**Comment by ggsmith** [comment]
I am not using cddplus in any package I maintain.  Furthermore, no longer expect to want the cddplus to be included at any point in the future.

At some point in the past, I thought FourierMotzkin might interface with this software, but this perspective has changed (largely because of improvements in Normalize).
