### ISSUE TITLE
Break Sometimes Breaks Multiple Loops, Depending on Subsequent Code

### ISSUE THREAD

**Issue by David-GW** [Macaulay2/M2#2552]
The code
```
for i from 1 to 2 do
{
	print "start";
	for j from 1 to 2 do
	{
		if j == 2 then break;
	};
	--print "end";
};
```
should print
```
start
start
```
but only prints
```
start
```
which suggests that `break` is breaking both loops.

However, uncommenting `print "end";` prints
```
start
end
start
end
```
so adding code after the broken loop seems to affect the behaviour.

This occurs on both my local installation of 1.20 and the web interface.

**Comment by mahrud** [comment]
I think this has to do with your use of `{ .. }` rather than `( .. )`. For instance, this code does what you expected:
```m2
for i from 1 to 2 do
(
	print "start";
	for j from 1 to 2 do
	(
		if j == 2 then break;
	);
	--print "end";
);
```

However, I'm not exactly sure why uncommenting the second print statement changes the output, or where this behavior is documented. I suspect it's related to how M2 parses `,` and `;` differently inside `{ .. }` and `( .. )`. For instance:
```m2
 {1, 2; 3; 4}
{(1, 2; 3; 4)}
{(1, 2; 3;(4))}

 {1, 2; 3, 4}
{(1, 2; 3, 4)}
{(1, 2;(3, 4))}
```
In particular, I can't explain the following:
```m2
f = () -> for j to 1 list (j, break); f() == {}
g = () -> for j to 1 list (j; break); g() == {}

for i to 1 list f()
for i to 1 list g()

for i to 1 list (i, f()) -- unexpected!
for i to 1 list (i, g())
```

**Comment by DanGrayson** [comment]
Good catch!

Fixed in commit fb1affc44fff0a0cebf8106a4372438cff62335a

**Comment by mahrud** [comment]
Could you add a few tests that cover the expected behavior along with the commit?

**Comment by DanGrayson** [comment]
> Could you add a few tests that cover the expected behavior along with the commit?

Okay, will do.

**Comment by DanGrayson** [comment]
Mahrud, I added a test in commit 34085616ad092f3b633b6906ed1668a9f4e775b0
