### ISSUE TITLE
Set and delete

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2623]
Here's a wildly undefined behavior:
```m2
i1 : S = set {0,1,2};

i2 : delete(0, S)

o2 = set {0, 1, 2} -- maybe delete just doesn't work for Set?

o2 : Set

i3 : delete(1, S)

o3 = set {}        -- what on earth?

o3 : Set

i4 : delete(2, S)

o4 = set {0, 1, 2} -- O_o

o4 : Set

i7 : delete(S, 0)

o7 = {}

o7 : List

i8 : delete(S, 1)

o8 = {0}

o8 : List

i9 : delete(S, 2)

o9 = {0, 1}

o9 : List

i10 : delete(S, 3)

o10 = {0, 1, 2}

o10 : List

i11 : delete(S, 10)

o11 = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9} -- LOL
```

Reported by Connor Simpson.

**Comment by DanGrayson** [comment]
A glance at the documentation and code shows that "delete" was designed to work only on lists, not hash tables, which is why the results are surprising.  (It's deleting entries with a certain value, not entries with a certain key; all values in a set are 1.)

It would be useful to make it also work for hash tables.

Notice that `remove` is available for mutable hash tables.

**Comment by mahrud** [comment]
> "delete" was designed to work only on lists, not hash tables, which is why the results are surprising.

Then it should give an error.
