### ISSUE TITLE
Proper formatting of source code

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2655]
This is a minor issue, but the code in the documentation is not quite correctly formatted.
consider `help exponents` (or https://www.unimelb-macaulay2.cloud.edu.au/usr/share/doc/Macaulay2/Macaulay2Doc/html/_exponents.html)
The code section is produced with `M2CODE`, so in HTML is translated into a `<pre><code language="Macaulay2">...</code></pre>`.
so far, so good. but the code is invalid: it's
```
../../../../Macaulay2/m2/monoids.m2:120:30-120:50: --source code:
exponents RingElement   := f -> first \ listForm f
```
Note that the first line is not actually M2 code.
There's a quick and easy way to fix this: move `--source code:` to the start of the line.
But I think a better way would be proper formatting of the output of the command `code`, which should neatly separate the source location (possibly using the resurrected `FilePosition`) and the actual code.
In particular I'd love to have both `error` and `code` tag separately source location to make it easier to jump to the location in question in your editor.

**Comment by DanGrayson** [comment]
If you modify the format of that line, you'll also have to modify the code for the emacs function `M2-send-to-program-or-jump-to-source-code`, which will jump to the source code when RETURN is pressed on that line.

By the way, the source code position is wrong at my end -- it points to a non-existent file.  I wonder how that got screwed up.  It hasn't worked since the feature appeared in version 1.17.

**Comment by pzinn** [comment]
> If you modify the format of that line, you'll also have to modify the code for the emacs function `M2-send-to-program-or-jump-to-source-code`, which will jump to the source code when RETURN is pressed on that line.

that would be a small price to pay.
