### ISSUE TITLE
Raising a ring self-map to the 0 power should be legal

### ISSUE THREAD

**Issue by emo916math** [Macaulay2/M2#2792]
```
R = ZZ[x, y, z];
f = map(R, R, {y, x*z, x^2 + 1});

f^1
f^5
f^0
```

The commands `f^1` and `f^5` give the expected result, based on iterating `f`, but `f^0` gives an error "missing unit element," although the operation has a well-defined answer, namely the identity map. Hoping this isn't too hard to fix. I am running Macaulay2 version 1.21.

**Comment by mahrud** [comment]
I think it's easy to patch it in the top level, but probably the better fix is to ask @DanGrayson what is `oneE` and how to add it to the `RingMap` class:
https://github.com/Macaulay2/M2/blob/048c777dc703365e44c3865b2c1faed698b82b3a/M2/Macaulay2/d/actors.d#L508-L509

**Comment by d-torrance** [comment]
I did a little digging and `oneE` is just the `ZZ` object 1:

```m2
i1 : RingMap#1 = "foo"

o1 = foo

i2 : (id_ZZ)^0

o2 = foo
```
The `RingMap` class doesn't know the rings of its instances, so I think this feature would need to be added at top level.

**Comment by mahrud** [comment]
Might be better to modify the interpreter so that `T#1` is always a function that takes in an instance of `T` and returns an appropriate identity element.

**Comment by mikestillman** [comment]
# is the main indexing notation for M2.  It seems that using T#1 as the identity would be difficult to arrange, and in any case, maybe a function name would be more appropriate?

That said, redoing the RingMap class in the engine would be a good plan at some point.

**Comment by d-torrance** [comment]
`Matrix ^ ZZ` and `MonomialIdeal ^ ZZ` are similar cases and they both check if the power is 0 before dropping down to the interpreter:

https://github.com/Macaulay2/M2/blob/048c777dc703365e44c3865b2c1faed698b82b3a/M2/Macaulay2/m2/matrix.m2#L193-L195

https://github.com/Macaulay2/M2/blob/048c777dc703365e44c3865b2c1faed698b82b3a/M2/Macaulay2/m2/monideal.m2#L52-L56

What's the rationale for using `id_(target f)` for `f^0` when `f` is a rectangular matrix?  It seems like that should raise an error.

**Comment by mahrud** [comment]
> The symbol `#` is the main indexing notation for M2. It seems that using T#1 as the identity would be difficult to arrange, and in any case, maybe a function name would be more appropriate?

I don't understand what difficulty you're referring to. `T` is a hash table here so `#1` indicates a key, not an index. We could switch to `#id` if you prefer, and also change the other types (mostly rings and fields, I think) with `#1` defined.

One thing I don't understand is how `CC ^ ZZ` uses `BinaryPowerMethod` and `(1+ii)^0` works, but `CC#1` is not defined!

> What's the rationale for using `id_(target f)` for `f^0` when `f` is a rectangular matrix? It seems like that should raise an error.

`f^1 = f` always makes sense, so at least one of `f^0 * f^1 = f` or `f^1 * f^0 = f` should also makes sense. I'm guessing choosing the former is just convention.

Is there a reason `SimplePowerMethod` is used rather than the faster `BinaryPowerMethod`?

**Comment by d-torrance** [comment]
> One thing I don't understand is how `CC ^ ZZ` uses `BinaryPowerMethod` and `(1+ii)^0` works, but `CC#1` is not defined!

This puzzled me too!  It turns out that this is one of the `when` cases that are checked in `Expr ^ Expr` in `actors.d` before it finally looks for a binary method for `^`:

https://github.com/Macaulay2/M2/blob/048c777dc703365e44c3865b2c1faed698b82b3a/M2/Macaulay2/d/actors.d#L713-L715

> `f^1 = f` always makes sense, so at least one of `f^0 * f^1 = f` or `f^1 * f^0 = f` should also makes sense. I'm guessing choosing the former is just convention.

I'm not sure I agree with this convention, but regardless, whatever convention is used for matrices should likely also be used for ring maps.

**Comment by DanGrayson** [comment]
> Might be better to modify the interpreter so that `T#1` is always a function that takes in an instance of `T` and returns an appropriate identity element.

No, don't modify the interpreter to achieve that.  Just put the identity element into the hash table T under the key 1.

**Comment by d-torrance** [comment]
> No, don't modify the interpreter to achieve that. Just put the identity element into the hash table T under the key 1.

There is no unique identity element since the ring in question is arbitrary. 

See #2799 for a proposed fix, modeled after `Matrix ^ ZZ`.
