### ISSUE TITLE
[...] syntax for subtitution and precedence

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2943]
For the first time, I tried to use the [...] syntax for subtitution. It did not work as expected:
```
i1 : R=QQ[x]

o1 = R

o1 : PolynomialRing

i2 : P=x^2

      2
o2 = x

o2 : R

i3 : x*P[2]

o3 = 8

o3 : QQ
```
Obviously, I expected `4*x`. For example, by contrast,
```
i4 : f=x->x^2

o4 = f

o4 : FunctionClosure

i5 : x*f 2

o5 = 4x

o5 : R
```
Unless this precedence issue is fixed, I think the syntax is pretty useless...

**Comment by d-torrance** [comment]
I think the precedence for `[` was chosen with constructing polynomial rings in mind.  See the last paragraph of https://macaulay2.com/doc/Macaulay2-1.22/share/doc/Macaulay2/Macaulay2Doc/html/_parsing_spprecedence_cm_spin_spdetail.html

**Comment by mahrud** [comment]
1. Changing the precedence would probably break `ZZ/101[x]`
2. The syntax is pretty handy when you have multiple variables:
```m2
i23 : f = det random(R^{1}, R^1)

o23 = 13767x - 13433y + 5248z

o23 : R

i24 : f[1,2,3]

o24 = 2645

i25 : f[z,y,x]

o25 = 5248x - 13433y + 13767z

o25 : R

i26 : f[x,x,x]

o26 = 5582x

o26 : R

i27 : f[x,0,0]

o27 = 13767x

o27 : R
```
3. That said, I have wondered why it's `f[1,2,3]` rather than the more natural `f(1,2,3)`. All it takes is one line:
```m2
RingElement Sequence := (r,v) -> substitute(r,matrix {toList v})
```
The only downside is that `f(2)` won't immediately work, unless we also add:
```m2
RingElement RingElement :=
RingElement Number := (r,v) -> substitute(r,matrix {{v}})
```
I think given that for a function closure in one variable both `f 2` and `f(2)` are defined, for a polynomial in one variable defining `f 2` and `f (2)` would also be nice.

**Comment by mahrud** [comment]
Also, this last behavior in 1.22 seems wrong:
```m2
i1 : B = QQ[b]; A = B[a];

i3 : f = a + b

o3 = a + b

o3 : A

i4 : f[1,10]

o4 = 11

i5 : f[5]

o5 = 5
```
In development, it has changed due to #2863:
```m2
i3 : f = a + b

o3 = a + b

o3 : A

i4 : f[5]

o4 = b + 5

o4 : B

i5 : f[1,10]
stdio:6:1:(3): error: encountered values for 2 variables, but expected 1
```
c.f. #2944

**Comment by pzinn** [comment]
changing the precedence of `[...]` would make a mess. My preferred solution would be switching to `(...)` (including no parentheses at all), as suggested by @mahrud
