### ISSUE TITLE
Some Github builds hitting 6-hour time limit

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#2956]
There is a 6-hour time limit on Github actions (see https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits).  I'm not sure what changed, but we've hit this a few times recently (https://github.com/Macaulay2/M2/actions/runs/6446051912, https://github.com/Macaulay2/M2/actions/runs/6415396018, and https://github.com/Macaulay2/M2/actions/runs/6389495572, for example).  It used to usually run in about 4.5 hours I think.

One possible fix might be to break the builds up into multiple "jobs" which hopefully would each run for far less than six hours, and then assign a dependency relationship between them.

**Comment by mahrud** [comment]
Seems like autotools takes about twice as long as cmake. Why not stop running the tests on the autotools build and just run them with cmake?

**Comment by mahrud** [comment]
Seems to have fixed itself. Maybe the Github cache had expired.

**Comment by mahrud** [comment]
Here are timings from a recent build:
- Without tests:
  - [cmake-macos-12-clang-15](https://github.com/Macaulay2/M2/actions/runs/7437548367/job/20235325223#logs), 1h 32m 20s
  - [autotools-macos-12-default](https://github.com/Macaulay2/M2/actions/runs/7437548367/job/20235325100#logs), in 4h 23m 13s
- With tests:
  - [cmake-ubuntu-22.04-clang-15](https://github.com/Macaulay2/M2/actions/runs/7437548367/job/20235325165#logs), in 2h 12m 42s
  - [autotools-ubuntu-22.04-default](https://github.com/Macaulay2/M2/actions/runs/7437548367/job/20235325044#logs), in 3h 34m 29s

Is the cmake build not running some test, or is autotools just significantly slower?

Also, the main branch has been stuck on the same commit [86d6c70](https://github.com/Macaulay2/M2/commit/86d6c70f8746e6b13d95c53ad20d880e0d60a8dc) since **Oct 26** and running the same actions over and over again, and failing it for at least a couple of months. @DanGrayson do you want to remove the nightly build if it's being ignored anyway?

**Comment by mikestillman** [comment]
@DanGrayson Can you replace the main/master branch with development?  Or should I do that?

**Comment by mikestillman** [comment]
@d-torrance @DanGrayson Do you see if there are any obvious speedups for the autotools build?

**Comment by d-torrance** [comment]
I think one of the big differences is in the time it takes to build the documentation.

Let's take a look at each of the builds, from when they start installing `FirstPackage` to when they finish installing `OIGroebnerBases`, using the actions from my recent PR (https://github.com/Macaulay2/M2/actions/runs/7429147236):

| Build | Start Time | Finish Time | Elapsed Time |
| --------| ---------------- | ---------------- | ------------------------ |
| cmake-ubuntu-22.04-default | 3:29 | 4:40 | 1:11 |
| autotools-ubuntu-22.04-default | 3:33 | 5:43 | 2:10 |
| autotools-macos-12-default | 3:39 | 7:34 | 3:55 | 
| cmake-ubuntu-22.04-clang-15 | 3:29 | 4:41 | 1:12 |
| cmake-macos-12-clang-15 | 3:39 | 5:30 | 1:51 |

It seems like, roughly, the Ubuntu machines are about twice as fast as the macOS ones, and the cmake build is about twice as fast as the autotools build.

I can think of two possible speedups for the autotools buid:

* Turn off the verbose logging (my fault -- see #2049).  I don't know how significant it is, but we're probably spending a fair amount of time doing all that extra printing.
* Try building in parallel with `make`'s `-j` option.  (That's what `ninja` does by default, I believe, which is probably why the cmake build is so much faster.)

**Comment by mahrud** [comment]
We could skip building with autotools on mac and running tests on auto tools.

**Comment by DanGrayson** [comment]
I'll do it.
