### ISSUE TITLE
cmake build should get location of ffi.h from pkg-config

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#2965]
On my system I have
```
# pkg-config -cflags libffi 
-I/usr/lib64/libffi/include
```
but the build breaks with 
```
M2/M2/Macaulay2/d/ffi.d:7:18: fatal error: ffi.h: No such file or directory
    7 |         #include <ffi.h>
      |                  ^~~~~~~
```

**Comment by mahrud** [comment]
My understanding is that importing dependencies via `find_package` and a `FindBlah.cmake` script is preferred to using `pkg-config`, which is very rigid and in many cases (c.f. #1227 and #1498) the root cause of hard to debug compilation errors, which is why I'd like to use `find_package` for fflas and givaro as the only two libraries currently added via `pkg-config`:
https://github.com/Macaulay2/M2/blob/379c9634000dd87221dc353e1aaaca413f75c81c/M2/cmake/check-libraries.cmake#L166-L168

If you could provide more info, I could try to help figure out why cmake isn't finding ffi correctly on your system.

**Comment by dimpase** [comment]
> If you could provide more info, I could try to help figure out why cmake isn't finding ffi correctly on your system.

On my system, and on Gentoo in general, the FFI headers are not installed in a standard location known by the compiler. 
The only way to find it is by calling pkg-config, as far as I can see. In fact I had a branch with an explicit call to pkg-config (in the same manner you did it for the version of FFI - but actually cmake has a macro for exactly this, `pkg_get_variable`), but then I replaced it by the call to `pkg_` macro.

I am not at all convinced by your argument that it's better not to use this macro. While it might be harmful to blindly get the CFLAGS pkg-config provides (FFI_CFLAGS) added to your CFLAGS/CPPFLAGS (as I understand was the reason for bugs you described), I don't do this in my branch.

**Comment by mahrud** [comment]
There are certainly ways to give cmake hints about non-standard locations, and that's perfectly fine.

I'll try the build on Gentoo soon and let you know. In the meantime, I don't think the gc fix needs to wait for this, but it's up to you.

**Comment by dimpase** [comment]
> There are certainly ways to give cmake hints about non-standard locations, and that's perfectly fine.

Hardcoded hints aren't really a solution, IMHO.
The only reliable way is to find the headers location is via pkg-config. Indeed, libffi allows its headers to go to a user-configured directory, via `--includedir=` configure switch.
