### ISSUE TITLE
Homogeneity bug in PushForward package

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3077]
Here is a basic example from docs for `reesAlgebra`:
```m2
needsPackage "PushForward"
needsPackage "ReesAlgebra"

kk = ZZ/101;
S = kk[x_0..x_4]
I = trim monomialCurveIdeal(S, {2,3,5,6})
R = reesAlgebra I
f = map(R, S, DegreeMap => prepend_0)
assert isHomogeneous f
```
It seems like `pushForward` from Core works fine but `pushFwd` loses homogeneity:
```m2
isHomogeneous(N = coker basis(2, R^1)) -- true
isHomogeneous pushForward_f N          -- true
isHomogeneous pushFwd_f N              -- false
```

**Comment by Devlin-Mallory** [comment]
In this example, the homogeneity is lost in the function makeModule in PushForward.m2, which is called by pushFwd. In particular, the issue arises in the following line in the code for makeModule:
`mp := if isHomogeneous f then 
               try(map(auxN,,f,matB**gens N)) else map(auxN,A^k,f,matB**gens N)
           else
               map(auxN,A^k,f,matB**gens N);
`
(the f in the code is not your f above, to be clear). 

The issue is that `map(auxN,,f,matB**gens N)` returns `error: degreeLift: degree not liftable`, despite the homogeneity of auxN, f, and matB**gens N, and thus the inhomogeneous map `map(auxN,A^k,f,matB**gens N)` is used instead. 

I don't understand why the degree is not liftable here, and will try to dig around more to understand exactly what's happening here.

**Comment by mahrud** [comment]
Ah, right, I forgot that I made an issue about this in #2905 already ...
I'll just reference this bug there.
