### ISSUE TITLE
bug in ??= and mutable hash tables

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3351]
Why is this happening?
```m2
i1 : X = Proj QQ[x];

i2 : X.sheaf ??= ring X

o2 = QQ[x]

o2 : PolynomialRing

i3 : X.sheaf ??= ring X
stdio:3:9:(3): error: expected method to be a function or TYPE => function'
```
cc: @d-torrance

**Comment by d-torrance** [comment]
It's because `QQ[x]` is a `PolynomialRing`, which inherits from `Type`, and `Type ??=` is syntactic sugar for calling `installMethod` to install a `??=` method for a given type.  So it's yelling at us that `ring X` isn't a function.

Your use case definitely seems more important than having that particular syntactic sugar.  I'll open a PR soonish removing it (probably in the next few days).

**Comment by mahrud** [comment]
Hmm shouldn't the syntax for installing `??=` methods have a key like `((??=, =), Type, Type)`? What is an example of using this syntactic sugar?

**Comment by d-torrance** [comment]
Right now they key is just `??=`.  So `installMethod(symbol ??=, T, f)` will set it so that `x ??= y` (when `x` is an instance of `T`) will call `f(x, y)`.

I don't think the syntactic sugar is currently used anywhere outside of the documentation (see [installing augmented assignment methods](https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_installing_spaugmented_spassignment_spmethods.html)

**Comment by mahrud** [comment]
I'm not sure if I understand. In the bug above, is `Type ??= Type` triggering a syntactic sugar for installing a method on `(symbol ??=, Type)`? I can't figure out how to use this syntactic sugar without `installMethod`.

**Comment by d-torrance** [comment]
It's installing a method on `(symbol ??=, QQ[x])`
