### ISSUE TITLE
mathicgb: test fails on powerpc

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#339]
This is not directly related to Macaulay2, but [1] appears unmaintained.

The mathicgb package in Debian fails to build on several architectures, including powerpc [2].  I was able to reproduce the failed build, and have pasted the unittest.log file below.  Any ideas on what could be going wrong?

Thanks!

[1] https://github.com/broune/mathicgb
[2] https://buildd.debian.org/status/package.php?p=mathicgb

    [==========] Running 237 tests from 27 test cases.
    [----------] Global test environment set-up.
    [----------] 9 tests from Range
    [ RUN      ] Range.Simple
    [       OK ] Range.Simple (0 ms)
    [ RUN      ] Range.rangeToVector
    [       OK ] Range.rangeToVector (0 ms)
    [ RUN      ] Range.zip
    [       OK ] Range.zip (0 ms)
    [ RUN      ] Range.intRange
    [       OK ] Range.intRange (0 ms)
    [ RUN      ] Range.indexRange
    [       OK ] Range.indexRange (0 ms)
    [ RUN      ] Range.oppositePairRange
    [       OK ] Range.oppositePairRange (0 ms)
    [ RUN      ] Range.adjPairRange
    [       OK ] Range.adjPairRange (0 ms)
    [ RUN      ] Range.flatten
    [       OK ] Range.flatten (0 ms)
    [ RUN      ] Range.flattenRecursive
    [       OK ] Range.flattenRecursive (0 ms)
    [----------] 9 tests from Range (1 ms total)
    
    [----------] 1 test from IO
    [ RUN      ] IO.ideal
    [       OK ] IO.ideal (0 ms)
    [----------] 1 test from IO (0 ms total)
    
    [----------] 11 tests from GB
    [ RUN      ] GB.small
    FAIL unittest (exit status: 137)

**Comment by DanGrayson** [comment]
Could you work from https://github.com/Macaulay2/mathicgb instead?

**Comment by d-torrance** [comment]
I actually tried that first, but there isn't an "Issues" tab on that page.  If I recall, that's the default for forked repos, but you can add one in "Settings".

**Comment by DanGrayson** [comment]
Okay, I've turned on issues there, but by "work from" I meant only "get the code from", so you get the latest.

**Comment by d-torrance** [comment]
Ahhh, ok.  I've been basing my Debian packages for mathicgb (and memtailor and mathic) off of Bjarke Roune's repos and cherry-picking patches from the Macaulay2 repos as needed if I find problems.  Would you say that the Macaulay2 repos are the "official" upstream now?

**Comment by mikestillman** [comment]
Bjarke now works at google, and doesn’t have time for maintaining these packages.  Since I was a co-author on mathic and mathicgb, and I have write access to Bjarke’s repo’s, I am the maintainer, although perhaps Christian Eder is still interested in that too (he is a committer on mathicgb).  However, I have been making (small) changes only to the repo at Macaulay2.  One issue is that we had problems with the build system in mathicgb (at least, with linking it with Macaulay2), and so simplified it in the Macaulay2 fork.  I didn’t want to mess others up with changing Bjarke’s repo, but perhaps we should try to fix the build system there, and keep these two in sync.

But currently, we are working off the Macaulay2 fork.

At some point, I do plan on moving some of the code in mathicgb, which is not exposed to the user, to mathic, and to expose it.

— mike

**Comment by d-torrance** [comment]
Great, thanks for the info!

I'll try recreating the Debian package using the M2 fork and see if the powerpc build problem persists.  If so, I'll open a new issue there.

Closing this issue.  Thanks again!
