### ISSUE TITLE
determinant over quotient ring hangs

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3407]
Here the determinant is instantaneously zero over the field or even the polynomial ring, but it never finishes over the quotient ring:
```m2
det matrix(ZZ/32003[x]/(x),
       {{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},{0,-2,0,0,-2,0,0,0,0,0,0,1,0,0,0,0,3,0,0},{0,0,2,0,0,-1,0,0,0,3,0,0,-1,0,-3,
       0,0,1,0},{0,0,0,-2,0,0,1,1,0,0,3,0,0,0,0,0,0,0,3},{0,-1,0,0,3,0,0,0,3,0,0,2,0,3,0,0,3,0,0},{0,0,1,0,0,-1,0,0,0,0,0,0
       ,-1,0,1,0,0,-1,0},{0,0,0,2,0,0,3,-1,0,0,1,0,0,0,0,3,0,0,1},{0,0,0,0,0,0,-1,0,0,0,-1,0,0,0,0,1,0,0,-1},{0,-2,0,0,-2,0,
       0,0,0,0,0,1,0,0,0,0,3,0,0},{0,0,3,0,0,2,0,0,0,1,0,0,2,0,-1,0,0,-2,0},{0,0,0,2,0,0,3,-1,0,0,1,0,0,0,0,3,0,0,1},{0,-1,0
       ,0,-2,0,0,0,1,0,0,1,0,1,0,0,2,0,0},{0,0,-1,0,0,0,0,0,0,-3,0,0,0,0,-3,0,0,-2,0},{0,0,0,0,2,0,0,0,-2,0,0,-1,0,-2,0,0,-1
       ,0,0},{0,0,-2,0,0,-3,0,0,0,-1,0,0,-3,0,2,0,0,1,0},{0,0,0,0,0,0,2,0,0,0,2,0,0,0,0,-2,0,0,2},{0,2,0,0,-3,0,0,0,-2,0,0,-
       2,0,-2,0,0,3,0,0},{0,0,-3,0,0,-3,0,0,0,3,0,0,-3,0,-1,0,0,-1,0},{0,0,0,2,0,0,-2,-1,0,0,3,0,0,0,0,1,0,0,3}})
```

**Comment by Devlin-Mallory** [comment]
You may have gotten this far already, but if not: if you call that matrix m, the sticking point occurs when exteriorPower(19,m) calls rawExteriorPower(19, raw m, getMinorsStrategy(R)). Since R is the quotient of a polynomial ring, getMinorsStrategy(R) returns 1, corresponding to the "Bareiss" strategy (whatever that is). If you instead use one of the other strategies rawExteriorPower(19, raw m, 0) or rawExteriorPower(19, raw m, 2), you get 0 fairly instantaneously, so it appears the problem is with the Bareiss strategy for rawExteriorPower.
