### ISSUE TITLE
Frobby version number

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#383]
In [1], we get the frobby version number from stdinc.h, which will definitely exist if we've built frobby, but may not if we've installed the frobby shared library beforehand, e.g., by using the Debian package.

I suppose we could use AC_CHECK_HEADERS to see if it's there, and just paste the corresponding lines from stdinc.h into version.dd if it's not.

Ideally, it seems like this should be something that's included in frobby.h instead of stdinc.h  This is even suggested in header file itself [2].

[1] https://github.com/Macaulay2/M2/blob/4af5a550200754e6b44dc4f0e5cca47a49ad97b1/M2/Macaulay2/d/version.dd#L41
[2] http://anonscm.debian.org/cgit/debian-science/packages/frobby.git/tree/src/stdinc.h#n100

**Comment by DanGrayson** [comment]
I suggest an email to Bjarke Roune to remind him of [2].  Eventually, when we encounter a frobby in the wild, we can see whether it provides the version number and a way to access it.  If not, we can just omit the version number from our copyright message by putting the empty string there.  Pasting the corresponding lines into our source code would be wrong, because the library encountered may be of a different version when M2 is finally run, which may happen on a different machine under a different version of the OS.
