### ISSUE TITLE
Bug in isHomogeneous function with ideal(x,x+y^2)

### ISSUE THREAD

**Issue by heoa** [Macaulay2/M2#405]
I noticed too late that you have a separate bug-tracker page, emailed in Google page, but now reported also here. \langle x,x+y^2 \rangle is homogenous ideal but M2 returning false with isHomogenous. Bug.

Easy to reproduce
R=RR[x,y];
ii19 : isHomogeneous(ideal(x,x+y^2))
oo19 = false
ii20 : isHomogeneous(ideal(x,y^2))
oo20 = true
ii21 : ideal(x,y^2)==ideal(x,x+y^2)
oo21 = true

**Comment by DanGrayson** [comment]
It is documented to behave that way: "Modules are homogeneous if their generator and relation matrices are homogeneous."

Probably that is preferable to doing a computation to determine the answer, because the computation might be unbearably long and because a homogeneous ideal is almost always presented homogeneously.
