### ISSUE TITLE
Ubuntu 14.04 installation problem

### ISSUE THREAD

**Issue by princengoc** [Macaulay2/M2#510]
I am using Ubuntu 14.04, i686. 
In the installation package
Macaulay2-1.9.1-x86_64-Linux-Ubuntu-14.04.tar.gz 
which dated July 11, 2016, the file bin/M2 seems to be a script that calls M2-binary, which throws an error:
./M2-binary: 1: ./M2-binary: ELF: not found
./M2-binary: 2: ./M2-binary: @@@@@@00pp@p@@@t��t��: not found
./M2-binary: 3: ./M2-binary: �@�: not found
./M2-binary: 4: ./M2-binary: Syntax error: "(" unexpected

**Comment by DanGrayson** [comment]
You have a 32 bit system, as indicated by i686, but you're using our 64 bit binary, as indicated by x86_64, so it thinks the file M2-binary is a shell script rather than a binary executable file.

We haven't made any 32 bit binaries, since Macaulay2 computations often need so much memory.

I suggest compiling it yourself following our INSTALL instructions.  If that doesn't work out for you, let us know by reopening this issue.  Closing ...
