### ISSUE TITLE
need a way to disable or modify ulimit parameters globally

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#519]
... because some machines are slow, especially those being run in emulators.

Some limits are hard coded in `M2/Macaulay2/m2/html.m2`.  Some are set as
make-variables in files such as `M2/Macaulay2/packages/Macaulay2Doc/test/Makefile.test.in`.

Thanks to Brent Baccala for the suggestion.

**Comment by d-torrance** [comment]
This has been possible since `argumentMode` was introduced in 0158226:

```m2
i1 : debug Core

i2 : argumentMode = defaultMode - SetUlimit 
```

**Comment by d-torrance** [comment]
> **Written by Claude** (Claude Opus 5, via Claude Code), not by @d-torrance, whose account posted it -- please weigh it accordingly.

Reopening, because this closed on one of its two asks.

`argumentMode = defaultMode - SetUlimit` does settle **disable**. It does not
settle **modify**, and modify is what the pre-GitHub `bugs/` tree asked for --
three separate files, all still current:

- `bugs/dan/0-ulimit` — the limits used when building and when installing
  packages "should be derived from options to the configure script, so builders
  have easy access to them"
- `bugs/dan/0.1-ulimits` — "These limits should be overridable by: configure
  script options / make command line options / installPackage options", quoting
  the very line this issue names, then in `m2/html.m2`
- `bugs/dan/0-settable-memory-limits` — Dan replying to a build failure with
  "I'll plan to make those limits (memory and time) settable in the configure
  script, eventually"

Where each of those stands on 1.26.06-8-g34d5846039:

| | |
| --- | --- |
| disable | works, `argumentMode = defaultMode - SetUlimit` |
| modify, from configure | no option exists |
| modify, from make | yes for the test directories, no for the values used when running examples |
| modify, from installPackage | no; only all-or-nothing |

The line has moved from `m2/html.m2` to `M2/Macaulay2/m2/run.m2:13`, but it is
still the values written in:

```m2
ulimit := utest "-c unlimited" | utest "-t 700" | utest "-m 850000" | utest "-s 8192" | utest "-n 512"
```

and the binding is the reason modify is unreachable. `ulimit` is `:=`, so it is
local to that file; `argumentMode` and `SetUlimit` are exported into Core's
private dictionary and `ulimit` is not:

```m2
i1 : debug Core

i2 : (Core#"private dictionary")#?"argumentMode", (Core#"private dictionary")#?"SetUlimit"

o2 = (true, true)

i3 : (Core#"private dictionary")#?"ulimit"

o3 = false
```

So the values cannot be changed by any route short of editing `run.m2` and
rebuilding. The test directories are better off -- `TLIMIT`, `MLIMIT`, `VLIMIT`
and `SLIMIT` in `M2/Macaulay2/tests/Makefile.test.in` are `?=`, so `make
TLIMIT=300` works there -- but that covers `make check`, not the limits applied
while installing a package's examples.

One number worth having alongside this, from triaging `0-settable-memory-limits`:
the 2011 report there was a build failing because M2 wanted 974 MB of virtual
memory under `ulimit -v 850000`. M2 now reserves about 2.2 GB of address space at
startup for 124 MB resident, so every `-v` value still written into the makefiles
is below what it needs. The main test directory survives because 8ef9f80447
commented its `-v` out; `m2/basictests/Makefile.in` still applies its own at
600000.

<sub>From [`bugs/dan/0.1-ulimits`](https://github.com/Macaulay2/M2/blob/388c1ff0ce30d83751dea7bc7eac77fdc1305dd7/bugs/dan/0.1-ulimits) in the pre-GitHub `bugs/` tree, being triaged in [#36](https://github.com/Macaulay2/M2/issues/36).  Source of truth: [`bug-triage/catalog.tsv`](https://github.com/d-torrance/M2/blob/bug-triage/bug-triage/catalog.tsv).</sub>
