### ISSUE TITLE
homebrew gcc 4.9

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#549]
Our install instructions for Mac OS X specify using gcc 4.9 as provided by homebrew.  But under Mac OS 10.12, it builds programs that don't catch exceptions.  Try this one, for example:
```
#include <stdexcept>
#include <string>
int main () {
  const std::string s("caught");
  try { throw(std::runtime_error(s)); } 
  catch (std::runtime_error e) { }
  return 0;
}
```
So we have to come up with a workaround.  At home I'm building gcc myself from sources obtained from ftp.gnu.org, but that's a bit inconvenient.

Best solution: make M2 compile with gcc 5 and 6 and clang.  Then use clang for building binary distributions, since that's what the homebrew packages are built with.

**Comment by DanGrayson** [comment]
Compilation with clang almost works, so I think we will be able to use that.

**Comment by mikestillman** [comment]
The book output for toricHilbertSchemes is different under clang, gcc.  However, the differing output that clang gives is correct, just different. (I checked this by running them both, importing the ideal JM from one into the other M2, and checking equality.  Additionally, the lines right after o64 give an indication, if not quite a proof, that they are the same).

One way to get different, yet correct, output, is to be using different sort functions, as happens when we switch standard c++ libraries.  One way to get this to not be an issue is to use std::stable_sort instead of std::sort.

There are still several uses of std::sort.  I'm reluctant to change it right for this release, as it could change other behavior, and also change (positively, or more likely negatively) performance. Dan, what do you think?

**Comment by DanGrayson** [comment]
Let's switch to stable sort, so we don't have to think about this issue any longer.  Our time spent thinking is important, too.

**Comment by mikestillman** [comment]
OK. I'll change all uses to stable_sort, then recompile and test.

**Comment by mikestillman** [comment]
It would be good to have tests which check for large timing differences too.  I'm not sure how best to do that.

**Comment by DanGrayson** [comment]
For that, see https://github.com/Macaulay2/M2/issues/309

**Comment by DanGrayson** [comment]
Once all the sorts are stable, we can say again that when an answer is different, it's a bug.

**Comment by mikestillman** [comment]
I have changed all uses of std::sort to std::stable_sort.  Now the gcc version and the clang version each have 2 errors during 'make check'.  The first is probably unrelated, in BGG.  The second is the completeIntersections chapter.  Both the gcc and clang versions have the same error, and diff with the expected output.  Probably the new output is correct, but I need to check that carefully, I guess.

I haven't determined if changing this changes the performance of Groebner basis computation.  This could happen, because spairs can now be performed in a different order, or different reducers could be chosen during reduction.  I did not notice any serious slowdowns during 'make check', although I didn't really measure it carefully.

**Comment by DanGrayson** [comment]
Habanero's Ubuntu 14 g++ doesn't offer c++ 14, so I'm putting it back to
c++ 11.  Was that important?

When you get a chance, take a look at your other issues for 1.9.3 and
decide whether to solve them
or put them off to 2.0.

**Comment by mikestillman** [comment]
What about -std=c++1y, does that work?  gcc4.9 is supposed to be C++14 feature complete.

Currently, I am only using c++-14 for some debugging code, so I can get by without it, but it does simplify the language considerably in certain uses. Also, 2014 is 3 years old now...

Should I update habanero to 16.04 in any case?  We don’t care about supporting that system anymore?

**Comment by DanGrayson** [comment]
It's g++ 4.8 on Ubuntu 14.  1y does work, but I wouldn't want to use it.
Ubuntu 14.04 is supported
until 2019, so we should support it, too, the theory being that we will
find departments using it still.

**Comment by mikestillman** [comment]
OK, sounds good. I’ll either avoid use of c++14, or ifdef it.

**Comment by DanGrayson** [comment]
ifdeffing would not be so good, because then a test might fail on one
system but not on another

**Comment by mikestillman** [comment]
Still, 2 more years with not using it might be excessive.  I will also check c++1y support on gcc 4.8, just to see what the support level is. After all, I’m not using hard parts of c++14…

**Comment by DanGrayson** [comment]
okay

**Comment by mikestillman** [comment]
ok, although failing on one system versus another can always happen, as we are using different compilers and/or versions for all of these systems.

**Comment by DanGrayson** [comment]
Yes, but such ifdeffing makes it more likely to happen.

**Comment by mikestillman** [comment]
Did you change c++14 back to c++11?  I don’t see it in the repo.

**Comment by DanGrayson** [comment]
okay, just pushed it

**Comment by mikestillman** [comment]
Looking at the output of the complete intersections chapter, the calls to ```time rH' = Ext(M,N')``` on line 221, the outputs differ (from gcc4.9, from clang).  They are most likely isomorphic, as just some coefficients are different, on 6 generators of the Ext module.

Dan, do you have a good way to check correctness of this module?  I guess we can import the module from the clang M2 into the other M2, compute Hom(one,other), take a random map of degree 0 in there, and see if it is an isomorphism.  But perhaps you have a better method...

**Comment by DanGrayson** [comment]
Look at diffs for the log of the file test.out.expected, and you'll see I've changed the expected output many times without being so careful, so one more time shouldn't matter.  Maybe even the new answers agree with one of the old answers.  Look at the diffs.

**Comment by mikestillman** [comment]
Expected output for completeIntersections chapter changed in commit dbb9caea7

**Comment by DanGrayson** [comment]
Okay, I just rebuilt everything with clang, and the only failing tests are internal tests for givaro and ffpack, and the only reason they fail is because of missing include files.  Mike, can you figure those two out?

**Comment by mikestillman** [comment]
I'll take a look. But it might be more worthwhile to upgrade to the latest givaro, ffpack.

**Comment by DanGrayson** [comment]
That's a great idea.  I've advanced the milestone on #513 .

**Comment by DanGrayson** [comment]
Building gcc 4.9.4 from source on mac os x and using it makes the interrupt handling work.

**Comment by mikestillman** [comment]
I recommend pushing this back to 2.0

**Comment by DanGrayson** [comment]
Okay.  We can compile with clang now, and perhaps later versions of gcc will work, too (?).
