### ISSUE TITLE
Macaulay2/tests should be moved

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#990]
There is a lone test here (well, 4 related tests).  This should be moved to `Macaulay2Doc/test`? (Thanks to @mahrud for noticing this lone test...!)

**Comment by DanGrayson** [comment]
The name `Macaulay2Doc` implies the directory is about documentation, so maybe not, and instead, migrate all the tests in the opposite direction.

**Comment by mahrud** [comment]
Related to the docs, is there a way to reinstall `Macaulay2Doc` from the interface (i.e., without recompiling)? It's difficult to work on documentation for core methods without the ability to see the results. Here's the error resulting from running `installPackage "Macaulay2Doc"`:
```
Projects/M2/M2/M2/Macaulay2/packages/Macaulay2Doc/overview_packages.m2:7:1:(2):[18]: error: mutable unexported unset symbol(s) in package FThresholds: 'fastExponentiation'
/usr/share/Macaulay2/FThresholds/MainFunctions.m2:62:31-62:49: here is the first use of 'fastExponentiation'
```
Interestingly, if you run it again the error changes (maybe because `fastExponentiation` is now in the dictionary?)

**Comment by DanGrayson** [comment]
It works for me.  Could try again, this time with "-q" on the M2 command line?

**Comment by mikestillman** [comment]
On the `eigen` branch, I have moved the doc in `Macaulay2/packages/Macaulay2Doc/test` to `Macaulay2/tests`.
